### ISSUE TITLE
How to troubleshoot/ Error shown on driving time

### ISSUE THREAD

**Issue by irsx02** [qistoph/MMM-MyCommute#14]
Hi, 

 First, thanks for maintaining this module - this is quite useful for my morning drive.

 I'm having an issue where the drive time on Magic Mirror is showing "Error."  As in, I see my label for my destination, followed by the red "Error" text for the drive time.  I've check the address with maps.google.com and it exists; it'll show the travel time.  I've logged into the google cloud platform and I've enabled Maps Javascript API, Directions API, and Geocoding API.  

 Whenever I load up Magic Mirror, I can see the error counts show up in the google cloud dashboard, so I know the apiKey is working.  

 Whats the best way to start diagnosing the problem?  Is there any way to see the error message generated?  I'm familiar with Java (but not JavaScript).  I've tried tracing the MyCommute code down to line 462, where the ERROR message is set,  but I don't know exactly what the error message is.

 Any help is most appreciated.

**Comment by enjoynering** [comment]
Hello,

I have install the module right now and I have the same problem.

I hope to solve it.

Thank you for making our lifes easier :) I love this type of modules.

**Comment by qistoph** [comment]
Good question! I'm sorry you're having issues. Maybe it's a good idea to write some troubleshooting steps in the README. I'll try and make some time this week

**Comment by qistoph** [comment]
Since it was just a few minutes of work, some additional error handling is now available.

Please update to the latest version and follow the Troubleshooting steps:
https://github.com/qistoph/MMM-MyCommute#troubleshooting

Feel free to re-open this issue if errors still persist or if have suggestions to improve the error handling.

**Comment by irsx02** [comment]
No need for apologies.  This module is awesome. I'm ready to start debugging once I get some free time.
