### ISSUE TITLE
Can someone help me with my adresses?

### ISSUE THREAD

**Issue by ToMoSK1** [qistoph/MMM-MyCommute#22]
Hey guys im totally new to this and im trying to get this working. I managed to get the module on the screen it shows loading indefinetly i think i just put the adresses wrong, i really dont know how to add it there. if someone can help me how to formulate it i would really appreciate it!

Adress 1: https://goo.gl/maps/aRcCEetg3f11dZUo9
Adress 2: https://goo.gl/maps/qZD1SWUr3DP8QApa9
Origin Adress: https://goo.gl/maps/KG1BzbZwxAZfNpds7
i tried from origin adress to way on 1 like this:
`{
  module: 'MMM-MyCommute',
      position: 'top_right',
      header: 'MHD',
      classes: 'default everyone',
  config: {
    apiKey: 'MY API KEY',
    origin: 'Raketová 1472/1, Košice, 040 12',
    startTime: '00:00',
    endTime: '23:59',
    hideDays: [],
    destinations: [
      {
				destination: "Námestie osloboditeľov 3377/1, Košice, 040 01",
				label: "Mesto",
				mode: "transit",
				time: null
			},
    ]`

**Comment by ivanovd** [comment]
Try this:
Origin: 'Raketová 1472/1, 040 12 Nad jazerom, Slovakia'
Destination: 'Námestie osloboditeľov 3377/1, 040 01 Staré Mesto'
Destination #2: 'Alza.sk, Žriedlová 11, 040 01 Košice, Slovakia'

**Comment by radokristof** [comment]
You can use GPS coordinates also instead of postal address. That way the address can't be wrong.

**Comment by c-m0s** [comment]
The search-algorithm was much more tolerant a couple of years ago, when I originally installed my MagicMirror. Now I don't find another working solution than providing GPS-Coordinates, like @radokristof suggested, I must say.
In that case the parameter is still a `string` for origin and/or destination:

e.g.
`destination: "48.137395,11.5743542",`

**Comment by ivanovd** [comment]
It works with string addresses for me.

**Comment by radokristof** [comment]
No one said that it won't work with postal addresses. However if you use a postal address, anyway it will parse it first into a GPS coordinate and then provide a calculated direction. This parsing is mostly correct, but if it can't parse it correctly, then it will provide a wrong GPS coordinate, thus the calculation will be wrong.
