### ISSUE TITLE
Google API error 

### ISSUE THREAD

**Issue by sydios** [qistoph/MMM-MyCommute#24]
Hello,

I always get this error: Error: You must use an API key to authenticate each request to Google Maps Platform APIs. For additional information, please refer to http://g.co/dev/maps-no-account

I have billing enabled on my google account as well as the Directions API. It worked before I updated my MM and reinstalled this plugin. Any ideas why this is not working? I also created a new project and new API keys multiple times but no luck either.

Thanks!

**Comment by deyawper** [comment]
Related: I have the same situation as you. I noticed on the Google API that there was a warning asking for OAuth consent and domain verification. I'm a newbie to this but, does Google now require authentication and domain tracking in the app? I think MMM-MyCommute will need to be updated to support this, no?

**Comment by TheDuffman85** [comment]
I also ran into this problem after switching from antoher fork. Note that the property here is apiKey with a capital K. The property is case sensitive.

**Comment by qistoph** [comment]
That sounds like a reasonable explanation. I have updated the code to accept `apiKey` as well as `apikey` from the config.

The change to `apiKey` (capitcal K) was accidentally included with a PR. I would have preferred to maintain interoperability with other forks, but also don't want to break the module for people who had just changed to the capital K config.

The fix in https://github.com/qistoph/MMM-MyCommute/commit/a915657db3f62826f42596f78d7ae27707587e5f is the best solution, I guess.
