### ISSUE TITLE
Bug: Module loads infinitely after todays commits

### ISSUE THREAD

**Issue by TheDuffman85** [qistoph/MMM-MyCommute#26]
Some commit from today seems to have broken something. The module loads infinitely. Did you test after the dependency update?

![grafik](https://user-images.githubusercontent.com/9296618/108852582-162e6800-75e6-11eb-9a67-5c371423420c.png)

**Comment by qistoph** [comment]
It is tested and running on my x64 VM. Currently having some issues with my actual mirror's SD card and unable to test there.

**Comment by qistoph** [comment]
Could you confirm you are still having this issue and provide more details from logs?

I have tested it on my actual mirror and it "works on my machine".

Did you run `npm install` after pulling the module's updated code?

**Comment by TheDuffman85** [comment]
Yes, I deleted the repository made a fresh clone and installed the dependencies. I'll look into it today what exactly the issue is.

**Comment by TheDuffman85** [comment]
Can be closed. I tried it again and it works. I guess yesterday I was in a wrong folder when I installed the dependencies. Sorry! I'll create a pull request  in a few minutes for a new feature to make up for that.
