### ISSUE TITLE
Bug: Not Making API requests

### ISSUE THREAD

**Issue by danieltmc** [qistoph/MMM-MyCommute#4]
**Describe the bug**
The module displays "Error" in red where the commute times should be.  I checked my Maps JavaScript API and it does not show any API requests being made by the module.

**To Reproduce**
1. Format the config.js for the MagicMirror as follows (replacing the destinations and the API key):
```JavaScript
{
  module: 'MMM-MyCommute',
  position: 'top_left',
  config: {
    apikey: 'API_KEY_FROM_GOOGLE',
    origin: '65 Front St W, Toronto, ON M5J 1E6',
    startTime: '00:00',
    endTime: '23:59',
    hideDays: [0,6],
    destinations: [
      {
        destination: '14 Duncan St Toronto, ON M5H 3G8',
        label: 'Air Canada Centre',
        mode: 'walking',
        color: '#82E5AA'
      },
      {
        destination: '317 Dundas St W, Toronto, ON M5T 1G4',
        label: 'Art Gallery of Ontario',
        mode: 'transit'
      },
      {
        destination: '55 Mill St, Toronto, ON M5A 3C4',
        label: 'Distillery District',
        mode: 'bicycling'
      },
      {
        destination: '6301 Silver Dart Dr, Mississauga, ON L5P 1B2',
        label: 'Pearson Airport',
        avoid: 'tolls'
      }
    ]
  }
}
```
2. Restart the MagicMirror (pm2 restart mm)
3. Wait for the module to load and display the error message

**Expected behavior**
Expected to see commute times to the right of the destination names.

**Screenshots**
![IMG_14341_20190724_224558](https://user-images.githubusercontent.com/9474250/61842530-8c954200-ae66-11e9-910b-30b3d2ecdea0.jpg)

![Screenshot_4](https://user-images.githubusercontent.com/9474250/61842872-b733ca80-ae67-11e9-887d-a7bc258d8661.png)

**Running version**
I am running the most recent commit (May 20). I will include the hash when I get a chance.

**Additional context**
I used this module in the past (roughly one year ago) without issue.  I just recently started using my MagicMirror again and noticed Google Cloud Platform organizes the various APIs differently.  It is possible that the issue is due to the changes in the API, I am using the Maps JavaScript API since it was not 100% clear which API is to be used.

**Comment by qistoph** [comment]
There might be an issue with your API key or its permissions. The API key should have permissions to access the Directions API.

Did you check the error log of MagicMirror?
- If it's running from the shell, it should just be on the screen.
- If it's running from PM2, check `.pm2/logs/mm-error.log`

**Comment by qistoph** [comment]
Closing this, due to inactivity. If you need additional help, please re-open this issue.

**Comment by leofaoro** [comment]
I had this issue, I had to create a Google Cloud billing account.

**Comment by poonasor** [comment]
this happened to me a few weeks back - didn't have time to look into it until now. 

it seems my 12 months / $200 trial is up and google wants to put me on a pay as you go account / billing - not sure what to do now.. i might need to get back on the free tier.. any suggestions?

**Comment by qistoph** [comment]
Dear @poonasor,

The README was recently updated to include information on the free trail and billing:
https://github.com/qistoph/MMM-MyCommute#billing

I trust this information would be sufficient for you to get the information you're looking for and get the module working again. if you have any additional questions, feel free to ask here.
