### ISSUE TITLE
Bug: Update Description

### ISSUE THREAD

**Issue by itmelelsi** [qistoph/MMM-MyCommute#5]
Reading from previously open issues, a few suggestions to help:

Under initial description, update "Google's Traffic API" to "Google's Directions API" and hyperlink to API (https://console.cloud.google.com/marketplace/details/google/directions-backend.googleapis.com?folder=&organizationId=&project=arboreal-pen-251823).

Under Installation, modify point 3 to include "Go to Google Maps devtools, get an API key, and enable Directions API from library". Add a note that if you receive an ERROR in the MagicMirror application, that the user may need to verify a Billing Account has been added under for the API project in Google Cloud Platform. Or link directions on how to get started with Google's API projects. 

Thanks!

**Comment by qistoph** [comment]
Thanks for you suggestions!

Fixed in https://github.com/qistoph/MMM-MyCommute/commit/2bf41f7e9d851132bb51f70dd4935a5b2d2748d9.
