### ISSUE TITLE
Bug: cant get alternative routes just gives 1

### ISSUE THREAD

**Issue by sy8282** [qistoph/MMM-MyCommute#8]
```
 module: 'MMM-MyCommute',
                         position: 'top_left',
                         config: {
                         apikey: '',
                         origin: '',
                         startTime: '00:00',
                         endTime: '23:59',
                         hideDays: [0,6],
                         showSummary: true,
                         destinations: [
                                {
                                  destination: '',
                                  label: '',
                                  mode: 'driving',
                                  color: '#82E5AA',
                                  alternatives: true,
                                 }
                               ]
                            }
```

no idea where im going wrong any help would be appreciated

**Comment by qistoph** [comment]
Your config looks fine. Do you get any alternatives if you use Google Maps with the exact same `origin` and `destination`?

**Comment by sy8282** [comment]
yes with google maps on the webbrowser it gives 3 routes

**Comment by qistoph** [comment]
Could you share the origin and destination that you're having this issue with?
Or find a different combination that shows the same behavior?
Did you make sure you're running the latest version?

**Comment by sy8282** [comment]
i changed the house number to just the street and now all 3 routes show up
think its just a weird google issue, thanks for replying and checking it
wasnt me messing up the code.

**Comment by qistoph** [comment]
Thanks for reporting back. I'll close the issue
